export const lawyers = [
  {
    id: 1,
    nameFA: "دکتر علی محمدی",
    nameEN: "Dr. Ali Mohammadi",
    titleFA: "وکیل پایه یک دادگستری",
    titleEN: "Licensed Bar Attorney",
    specialtyFA: "حقوق مدنی و تجاری",
    specialtyEN: "Civil & Commercial Law",
    experience: 22,
    cases: 850,
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop",
    bioFA: "دکتر محمدی با بیش از ۲۲ سال تجربه در زمینه حقوق مدنی و تجاری، در پرونده‌های پیچیده قراردادی و شرکتی تخصص دارد.",
    bioEN: "Dr. Mohammadi, with over 22 years of experience in civil and commercial law, specializes in complex contractual and corporate cases.",
  },
  {
    id: 2,
    nameFA: "خانم سارا احمدی",
    nameEN: "Ms. Sara Ahmadi",
    titleFA: "وکیل پایه یک دادگستری",
    titleEN: "Licensed Bar Attorney",
    specialtyFA: "حقوق خانواده و امور ملکی",
    specialtyEN: "Family & Property Law",
    experience: 15,
    cases: 620,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop",
    bioFA: "خانم احمدی متخصص در پرونده‌های خانوادگی، طلاق، حضانت، مهریه و اموال ملکی است.",
    bioEN: "Ms. Ahmadi specializes in family cases, divorce, custody, dowry and property matters.",
  },
  {
    id: 3,
    nameFA: "آقای رضا کریمی",
    nameEN: "Mr. Reza Karimi",
    titleFA: "وکیل پایه یک دادگستری",
    titleEN: "Licensed Bar Attorney",
    specialtyFA: "حقوق کیفری",
    specialtyEN: "Criminal Law",
    experience: 18,
    cases: 740,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    bioFA: "آقای کریمی با ۱۸ سال تجربه در حقوق کیفری، یکی از برجسته‌ترین وکلای دفاع از متهمین در کشور است.",
    bioEN: "Mr. Karimi, with 18 years of criminal law experience, is one of the country's leading defense attorneys.",
  },
  {
    id: 4,
    nameFA: "دکتر مریم حسینی",
    nameEN: "Dr. Maryam Hosseini",
    titleFA: "وکیل پایه یک دادگستری",
    titleEN: "Licensed Bar Attorney",
    specialtyFA: "حقوق بین‌الملل",
    specialtyEN: "International Law",
    experience: 20,
    cases: 480,
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop",
    bioFA: "دکتر حسینی متخصص در حقوق بین‌الملل، داوری تجاری بین‌المللی و قراردادهای خارجی است.",
    bioEN: "Dr. Hosseini specializes in international law, international commercial arbitration and foreign contracts.",
  },
];

export const articles = [
  {
    id: 1,
    slug: "guide-to-filing-petition",
    titleFA: "راهنمای جامع تنظیم دادخواست در دادگاه‌های حقوقی",
    titleEN: "Comprehensive Guide to Filing a Petition in Civil Courts",
    excerptFA: "دادخواست مهم‌ترین سند در طرح دعوای حقوقی است. در این مقاله به بررسی مراحل تنظیم صحیح دادخواست می‌پردازیم.",
    excerptEN: "The petition is the most important document in civil litigation. This article examines the steps to properly draft a petition.",
    categoryFA: "حقوق مدنی",
    categoryEN: "Civil Law",
    author: "دکتر علی محمدی",
    authorEN: "Dr. Ali Mohammadi",
    date: "2024-12-01",
    readTime: 8,
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=400&fit=crop",
  },
  {
    id: 2,
    slug: "legal-rights-in-criminal-cases",
    titleFA: "حقوق متهم در پرونده‌های کیفری چیست؟",
    titleEN: "What Are the Rights of the Accused in Criminal Cases?",
    excerptFA: "آشنایی با حقوق قانونی متهم در مراحل مختلف دادرسی کیفری از دستگیری تا اجرای حکم",
    excerptEN: "Understanding the legal rights of the accused in various stages of criminal proceedings from arrest to sentence execution.",
    categoryFA: "حقوق کیفری",
    categoryEN: "Criminal Law",
    author: "آقای رضا کریمی",
    authorEN: "Mr. Reza Karimi",
    date: "2024-11-20",
    readTime: 12,
    image: "https://images.unsplash.com/photo-1479142506502-19b3a3b7ff33?w=800&h=400&fit=crop",
  },
  {
    id: 3,
    slug: "divorce-law-iran",
    titleFA: "قوانین طلاق در ایران: حقوق زن و مرد",
    titleEN: "Divorce Laws in Iran: Rights of Men and Women",
    excerptFA: "بررسی جامع قوانین طلاق، شرایط، مراحل و حقوق طرفین در جریان دعوای طلاق",
    excerptEN: "Comprehensive review of divorce laws, conditions, procedures and rights of parties during divorce proceedings.",
    categoryFA: "حقوق خانواده",
    categoryEN: "Family Law",
    author: "خانم سارا احمدی",
    authorEN: "Ms. Sara Ahmadi",
    date: "2024-11-10",
    readTime: 15,
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=400&fit=crop",
  },
  {
    id: 4,
    slug: "commercial-contracts",
    titleFA: "نکات مهم در تنظیم قراردادهای تجاری",
    titleEN: "Key Points in Drafting Commercial Contracts",
    excerptFA: "آشنایی با مهم‌ترین بندهای قرارداد تجاری و نکاتی که باید پیش از امضا بررسی کنید",
    excerptEN: "Understanding the most important clauses in commercial contracts and points to review before signing.",
    categoryFA: "حقوق تجاری",
    categoryEN: "Commercial Law",
    author: "دکتر مریم حسینی",
    authorEN: "Dr. Maryam Hosseini",
    date: "2024-10-30",
    readTime: 10,
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&h=400&fit=crop",
  },
  {
    id: 5,
    slug: "property-transfer",
    titleFA: "مراحل قانونی انتقال ملک و سند",
    titleEN: "Legal Steps for Property and Title Transfer",
    excerptFA: "گام به گام با فرآیند خرید، فروش و انتقال رسمی ملک در دفاتر اسناد رسمی",
    excerptEN: "Step-by-step guide to the process of buying, selling and official property transfer at notary offices.",
    categoryFA: "امور ملکی",
    categoryEN: "Property Law",
    author: "خانم سارا احمدی",
    authorEN: "Ms. Sara Ahmadi",
    date: "2024-10-15",
    readTime: 7,
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=400&fit=crop",
  },
  {
    id: 6,
    slug: "notice-vs-complaint",
    titleFA: "تفاوت اظهارنامه و شکواییه چیست؟",
    titleEN: "What Is the Difference Between a Legal Notice and a Complaint?",
    excerptFA: "بررسی تفاوت‌های اساسی میان اظهارنامه و شکواییه و کاربرد هر یک در پرونده‌های حقوقی",
    excerptEN: "Examining the fundamental differences between a legal notice and a criminal complaint and the use of each in legal cases.",
    categoryFA: "حقوق مدنی",
    categoryEN: "Civil Law",
    author: "دکتر علی محمدی",
    authorEN: "Dr. Ali Mohammadi",
    date: "2024-10-01",
    readTime: 6,
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
  },
];

export const faqs = [
  {
    questionFA: "هزینه مشاوره اولیه چقدر است؟",
    questionEN: "How much does an initial consultation cost?",
    answerFA: "اولین جلسه مشاوره کاملاً رایگان است. پس از بررسی پرونده، هزینه‌های وکالت با توجه به پیچیدگی پرونده تعیین می‌شود.",
    answerEN: "The first consultation session is completely free. After reviewing the case, attorney fees are determined based on case complexity.",
  },
  {
    questionFA: "مدت زمان تهیه اوراق قضایی چقدر است؟",
    questionEN: "How long does it take to prepare legal documents?",
    answerFA: "اظهارنامه و شکواییه معمولاً ظرف ۲۴ ساعت، دادخواست ظرف ۴۸ ساعت و لوایح قضایی ظرف ۷۲ ساعت آماده می‌شوند.",
    answerEN: "Notices and complaints are usually ready within 24 hours, petitions within 48 hours, and legal briefs within 72 hours.",
  },
  {
    questionFA: "آیا امکان مشاوره آنلاین وجود دارد؟",
    questionEN: "Is online consultation available?",
    answerFA: "بله، ما خدمات مشاوره آنلاین از طریق تماس ویدیویی و تلفنی ارائه می‌دهیم.",
    answerEN: "Yes, we offer online consultation services via video and phone calls.",
  },
  {
    questionFA: "در چه دعاوی تخصص دارید؟",
    questionEN: "What types of cases do you specialize in?",
    answerFA: "ما در دعاوی حقوقی، کیفری، تجاری، خانوادگی، ملکی و بین‌المللی تخصص داریم.",
    answerEN: "We specialize in civil, criminal, commercial, family, property and international cases.",
  },
];
